
###
GET http://localhost:9002/

###
POST http://localhost:9002/actuator/refresh

###
POST http://localhost:9002/books
Accept: *
Content-Type: application/json

{
  "author": "Jon Snow",
  "title": "",
  "isbn": "123ABC456Z",
  "price": 9.90
}